"""timezone, task audit fields, completion history, google calendar

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-06

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_sync_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=False),
    sa.Column('last_error', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_sync_jobs_task_id'), 'calendar_sync_jobs', ['task_id'], unique=False)
    op.create_table('google_accounts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('refresh_token_enc', sa.Text(), nullable=False),
    sa.Column('calendar_id', sa.String(length=255), nullable=True),
    sa.Column('sync_token', sa.String(length=512), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_error', sa.String(length=512), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('task_calendar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('etag', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'user_id', name='uq_task_calendar_events_task_user')
    )
    op.create_index(op.f('ix_task_calendar_events_event_id'), 'task_calendar_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_task_calendar_events_task_id'), 'task_calendar_events', ['task_id'], unique=False)
    op.create_index(op.f('ix_task_calendar_events_user_id'), 'task_calendar_events', ['user_id'], unique=False)
    op.add_column('tasks', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    op.add_column('tasks', sa.Column('completed_at', sa.DateTime(), nullable=True))
    op.add_column('tasks', sa.Column('completed_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_tasks_completed_by_id_users', 'tasks', 'users', ['completed_by_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('timezone', sa.String(length=64), server_default='Europe/Moscow', nullable=False))
    op.create_table('task_completions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('family_id', sa.String(length=10), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_completions_completed_at'), 'task_completions', ['completed_at'], unique=False)
    op.create_index(op.f('ix_task_completions_family_id'), 'task_completions', ['family_id'], unique=False)
    op.create_index(op.f('ix_task_completions_task_id'), 'task_completions', ['task_id'], unique=False)
    # Уже выполненные задачи: точное время неизвестно, считаем выполненными в момент миграции
    op.execute("UPDATE tasks SET completed_at = now() WHERE status = 'done' AND completed_at IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_completions_task_id'), table_name='task_completions')
    op.drop_index(op.f('ix_task_completions_family_id'), table_name='task_completions')
    op.drop_index(op.f('ix_task_completions_completed_at'), table_name='task_completions')
    op.drop_table('task_completions')
    op.drop_column('users', 'timezone')
    op.drop_constraint('fk_tasks_completed_by_id_users', 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'completed_by_id')
    op.drop_column('tasks', 'completed_at')
    op.drop_column('tasks', 'updated_at')
    op.drop_index(op.f('ix_task_calendar_events_user_id'), table_name='task_calendar_events')
    op.drop_index(op.f('ix_task_calendar_events_task_id'), table_name='task_calendar_events')
    op.drop_index(op.f('ix_task_calendar_events_event_id'), table_name='task_calendar_events')
    op.drop_table('task_calendar_events')
    op.drop_table('google_accounts')
    op.drop_index(op.f('ix_calendar_sync_jobs_task_id'), table_name='calendar_sync_jobs')
    op.drop_table('calendar_sync_jobs')
    # ### end Alembic commands ###
